// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMz6QD5yo2JYS6WR2Wui_X84otJM4X9gE',
    appId: '1:964391132757:web:4ed513aee7d428e4603edc',
    messagingSenderId: '964391132757',
    projectId: 'minutes-workout-app-87e2f',
    authDomain: 'minutes-workout-app-87e2f.firebaseapp.com',
    storageBucket: 'minutes-workout-app-87e2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEgAYE0Yr_C-5ujAPj3C0T61tjHg3EzLA',
    appId: '1:964391132757:android:c116bb3d5ec85280603edc',
    messagingSenderId: '964391132757',
    projectId: 'minutes-workout-app-87e2f',
    storageBucket: 'minutes-workout-app-87e2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSExuWFCd7LG9XSrxtuu-LSoTmCUz_HSo',
    appId: '1:964391132757:ios:dcf4c17978aa1c7b603edc',
    messagingSenderId: '964391132757',
    projectId: 'minutes-workout-app-87e2f',
    storageBucket: 'minutes-workout-app-87e2f.firebasestorage.app',
    iosBundleId: 'com.workout7min.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSExuWFCd7LG9XSrxtuu-LSoTmCUz_HSo',
    appId: '1:964391132757:ios:dcf4c17978aa1c7b603edc',
    messagingSenderId: '964391132757',
    projectId: 'minutes-workout-app-87e2f',
    storageBucket: 'minutes-workout-app-87e2f.firebasestorage.app',
    iosBundleId: 'com.workout7min.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMz6QD5yo2JYS6WR2Wui_X84otJM4X9gE',
    appId: '1:964391132757:web:4015b9f6611f407b603edc',
    messagingSenderId: '964391132757',
    projectId: 'minutes-workout-app-87e2f',
    authDomain: 'minutes-workout-app-87e2f.firebaseapp.com',
    storageBucket: 'minutes-workout-app-87e2f.firebasestorage.app',
  );
}
